#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM_DIR="$ROOT/wns-vm-adapters"
BENCH_DIR="$ROOT/Retreiver"
INSTALLER_DIR="$ROOT/wns-benchmark-adapter-installer"
LOG_DIR="$ROOT/logs"
PID_FILE="$LOG_DIR/embedding_service.pid"
DRY_RUN=0
SKIP_MODEL_SMOKE=0
SKIP_PIP=0
VM_HOST="${WNS_PUBLIC_HOST:-}"

usage() {
  cat <<'EOF'
Usage: bash setup_all_on_vm.sh [--host VM_HOST_OR_IP] [--skip-model-smoke] [--skip-pip] [--dry-run]

Does all VM setup in one command:
  1. Creates .env files with only ports 5000-5010.
  2. Installs VM embedding service requirements.
  3. Starts Qdrant, PGVector, and Weaviate with Docker Compose.
  4. Starts Jina/GTE embedding FastAPI service on port 5000.
  5. Installs benchmark adapters into Retreiver.
  6. Configures Retreiver/.env to point to this VM.
  7. Writes local frontend connection helper files.
  8. Runs syntax/config/service checks.

Options:
  --host HOST           Hostname/IP the local frontend should use to reach this VM.
                        If omitted, the script auto-detects the first non-loopback IP.
  --skip-model-smoke    Do not call /embed/jina and /embed/gte during setup.
                        Useful if model downloads are slow and you only want service health first.
  --skip-pip            Skip pip installs if dependencies are already installed.
  --dry-run             Validate script flow and write configs, but do not install/start services.
EOF
}

log() { printf '\n\033[1;36m[WNS setup]\033[0m %s\n' "$*"; }
warn() { printf '\n\033[1;33m[WNS setup warning]\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31m[WNS setup failed]\033[0m %s\n' "$*" >&2; exit 1; }
run() { echo "+ $*"; if [ "$DRY_RUN" -eq 0 ]; then "$@"; fi; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host) VM_HOST="${2:-}"; shift 2 ;;
    --skip-model-smoke) SKIP_MODEL_SMOKE=1; shift ;;
    --skip-pip) SKIP_PIP=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

require_file() { [ -e "$1" ] || fail "Required path missing: $1"; }
require_file "$VM_DIR/app/embedding_service.py"
require_file "$VM_DIR/docker-compose.vector-dbs.yml"
require_file "$BENCH_DIR/scripts/benchmark_cli.py"
require_file "$INSTALLER_DIR/scripts/install_adapters.sh"

if [ -z "$VM_HOST" ]; then
  VM_HOST="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [ -z "$VM_HOST" ]; then
  VM_HOST="127.0.0.1"
  warn "Could not auto-detect VM IP. Using 127.0.0.1. Re-run with --host VM_IP if local machine connects remotely."
fi

mkdir -p "$LOG_DIR"
log "Using VM host for local frontend connection: $VM_HOST"
log "Allowed host ports: 5000 embedding, 5001 Qdrant, 5002 Qdrant gRPC, 5003 PGVector, 5004 Weaviate, 5005 Jupyter optional"

if [ "$DRY_RUN" -eq 0 ]; then
  command -v python3 >/dev/null 2>&1 || fail "python3 is missing on VM"
  command -v docker >/dev/null 2>&1 || fail "docker is missing on VM"
  docker compose version >/dev/null 2>&1 || fail "docker compose is missing or not available"
fi

log "Writing VM service .env"
cat > "$VM_DIR/.env" <<EOF
WNS_PUBLIC_HOST=$VM_HOST
WNS_VM_HOST=0.0.0.0
WNS_EMBEDDING_PORT=5000
EMBEDDING_DEVICE=auto
JINA_MODEL_NAME=jinaai/jina-embeddings-v3
GTE_MODEL_NAME=Alibaba-NLP/gte-multilingual-base
WNS_EMBEDDING_API_KEY=
POSTGRES_USER=wns
POSTGRES_PASSWORD=wns_password
POSTGRES_DB=wns_benchmark
EOF

log "Writing benchmark .env, used by local dashboard/backend and VM benchmark runs"
cat > "$BENCH_DIR/.env" <<EOF
# Auto-generated by setup_all_on_vm.sh
WNS_PUBLIC_HOST=$VM_HOST
JINA_EMBEDDING_MODE=vm_remote
JINA_EMBEDDING_URL=http://$VM_HOST:5000/embed/jina
JINA_API_KEY=
JINA_EMBEDDING_MODEL=jina-embeddings-v3
GTE_EMBEDDING_MODE=vm_remote
GTE_EMBEDDING_URL=http://$VM_HOST:5000/embed/gte
HF_TOKEN=
GTE_EMBEDDING_MODEL=Alibaba-NLP/gte-multilingual-base
QDRANT_URL=http://$VM_HOST:5001
PGVECTOR_DSN=postgresql://wns:wns_password@$VM_HOST:5003/wns_benchmark
DATABASE_URL=postgresql://wns:wns_password@$VM_HOST:5003/wns_benchmark
WEAVIATE_URL=http://$VM_HOST:5004
QWEN_RERANK_URL=
AWS_REGION=
AWS_DEFAULT_REGION=
OPENAI_API_KEY=
EOF

log "Writing local frontend helper CMD files"
mkdir -p "$BENCH_DIR/scripts/windows"
cat > "$BENCH_DIR/scripts/windows/Configure-LocalFrontendForVM.cmd" <<'EOF'
@echo off
setlocal EnableExtensions
set VM_HOST=%~1
if "%VM_HOST%"=="" set VM_HOST=__VM_HOST_PLACEHOLDER__
if "%VM_HOST%"=="" (
  echo Usage: scripts\windows\Configure-LocalFrontendForVM.cmd VM_HOST_OR_IP
  exit /b 2
)
if not exist scripts\benchmark_cli.py (
  echo Run this from the Retreiver project root.
  exit /b 2
)
(
  echo WNS_PUBLIC_HOST=%VM_HOST%
  echo JINA_EMBEDDING_MODE=vm_remote
  echo JINA_EMBEDDING_URL=http://%VM_HOST%:5000/embed/jina
  echo JINA_API_KEY=
  echo JINA_EMBEDDING_MODEL=jina-embeddings-v3
  echo GTE_EMBEDDING_MODE=vm_remote
  echo GTE_EMBEDDING_URL=http://%VM_HOST%:5000/embed/gte
  echo HF_TOKEN=
  echo GTE_EMBEDDING_MODEL=Alibaba-NLP/gte-multilingual-base
  echo QDRANT_URL=http://%VM_HOST%:5001
  echo PGVECTOR_DSN=postgresql://wns:wns_password@%VM_HOST%:5003/wns_benchmark
  echo DATABASE_URL=postgresql://wns:wns_password@%VM_HOST%:5003/wns_benchmark
  echo WEAVIATE_URL=http://%VM_HOST%:5004
  echo QWEN_RERANK_URL=
  echo AWS_REGION=
  echo AWS_DEFAULT_REGION=
  echo OPENAI_API_KEY=
) > .env

echo Wrote .env for VM %VM_HOST%.
echo Now run: scripts\windows\Start-WnsDashboard-VM.cmd
endlocal
EOF
python3 - <<PY
from pathlib import Path
p=Path(r"$BENCH_DIR/scripts/windows/Configure-LocalFrontendForVM.cmd")
s=p.read_text()
s=s.replace('__VM_HOST_PLACEHOLDER__', '$VM_HOST')
p.write_text(s)
PY
cat > "$BENCH_DIR/scripts/windows/Start-WnsDashboard-VM.cmd" <<'EOF'
@echo off
setlocal EnableExtensions
if not exist scripts\serve_benchmark_dashboard.py (
  echo Run this from the Retreiver project root.
  exit /b 2
)
if exist .env (
  for /f "usebackq tokens=1,* delims==" %%A in (`type .env ^| findstr /v /r "^#"`) do set "%%A=%%B"
)
if not exist .venv (
  py -3 -m venv .venv
)
call .venv\Scripts\activate.bat
python -m pip install -r requirements-benchmark.txt
python scripts\check_services.py
start "WNS Benchmark Dashboard" http://127.0.0.1:8765
python scripts\serve_benchmark_dashboard.py 8765
endlocal
EOF

cat > "$BENCH_DIR/scripts/windows/Connect-Frontend-To-VM.cmd" <<'EOF'
@echo off
setlocal EnableExtensions
set VM_HOST=%~1
if "%VM_HOST%"=="" set VM_HOST=__VM_HOST_PLACEHOLDER__
if "%VM_HOST%"=="" (
  echo Usage: scripts\windows\Connect-Frontend-To-VM.cmd VM_HOST_OR_IP
  exit /b 2
)
if not exist scripts\benchmark_cli.py (
  echo Run this from the Retreiver project root.
  exit /b 2
)
call scripts\windows\Configure-LocalFrontendForVM.cmd %VM_HOST%
if errorlevel 1 exit /b %errorlevel%
python scripts\test_vm_connection.py
if errorlevel 1 (
  echo VM connection check failed. Confirm VM setup completed and ports 5000, 5001, 5003, 5004 are reachable.
  exit /b %errorlevel%
)
call scripts\windows\Start-WnsDashboard-VM.cmd
endlocal
EOF
python3 - <<PY
from pathlib import Path
p=Path(r"$BENCH_DIR/scripts/windows/Connect-Frontend-To-VM.cmd")
s=p.read_text()
s=s.replace('__VM_HOST_PLACEHOLDER__', '$VM_HOST')
p.write_text(s)
PY

cat > "$ROOT/LOCAL_FRONTEND_CONNECTION.md" <<EOF
# Local frontend connection

After this VM script completes, your local Retreiver frontend should use:

\`\`\`env
JINA_EMBEDDING_URL=http://$VM_HOST:5000/embed/jina
GTE_EMBEDDING_URL=http://$VM_HOST:5000/embed/gte
QDRANT_URL=http://$VM_HOST:5001
PGVECTOR_DSN=postgresql://wns:wns_password@$VM_HOST:5003/wns_benchmark
WEAVIATE_URL=http://$VM_HOST:5004
\`\`\`

On Windows CMD from the local Retreiver root, use the one-command launcher:

\`\`\`cmd
scripts\\windows\\Connect-Frontend-To-VM.cmd $VM_HOST
\`\`\`

This writes the local env file, tests VM connectivity, then starts the dashboard.

Manual fallback:

\`\`\`cmd
scripts\\windows\\Configure-LocalFrontendForVM.cmd $VM_HOST
scripts\\windows\\Start-WnsDashboard-VM.cmd
\`\`\`

If you cloned this package after the VM setup script was run, the VM host is embedded in \`Connect-Frontend-To-VM.cmd\` and \`Configure-LocalFrontendForVM.cmd\`. If not, pass the VM IP manually.
EOF

log "Installing VM Python requirements"
if [ "$SKIP_PIP" -eq 0 ]; then
  run python3 -m venv "$VM_DIR/.venv"
  if [ "$DRY_RUN" -eq 0 ]; then
    # shellcheck disable=SC1091
    source "$VM_DIR/.venv/bin/activate"
    python -m pip install --upgrade pip
    python -m pip install -r "$VM_DIR/requirements.txt"
    python - <<'PY'
try:
    import torch
    print('torch:', torch.__version__)
    print('cuda_available:', torch.cuda.is_available())
    if torch.cuda.is_available(): print('cuda_device:', torch.cuda.get_device_name(0))
except Exception as exc:
    print('torch check failed:', exc)
PY
    deactivate || true
  fi
else
  log "Skipping VM pip install"
fi

log "Starting vector databases"
if [ "$DRY_RUN" -eq 0 ]; then
  (cd "$VM_DIR" && docker compose -f docker-compose.vector-dbs.yml up -d)
else
  echo "+ (cd $VM_DIR && docker compose -f docker-compose.vector-dbs.yml up -d)"
fi

log "Starting embedding service on port 5000"
if [ "$DRY_RUN" -eq 0 ]; then
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    log "Embedding service already running with PID $(cat "$PID_FILE")"
  else
    (cd "$VM_DIR" && bash -c 'set -a; source .env; set +a; source .venv/bin/activate; nohup uvicorn app.embedding_service:app --host 0.0.0.0 --port 5000 > ../logs/embedding_service.log 2>&1 & echo $! > ../logs/embedding_service.pid')
  fi
  echo "Embedding service log: $LOG_DIR/embedding_service.log"
else
  echo "+ start uvicorn app.embedding_service:app --host 0.0.0.0 --port 5000"
fi

log "Installing benchmark adapters into Retreiver"
if [ "$DRY_RUN" -eq 0 ]; then
  bash "$INSTALLER_DIR/scripts/install_adapters.sh" "$BENCH_DIR"
else
  echo "+ bash $INSTALLER_DIR/scripts/install_adapters.sh $BENCH_DIR"
fi

log "Installing benchmark Python requirements"
if [ "$SKIP_PIP" -eq 0 ]; then
  run python3 -m venv "$BENCH_DIR/.venv"
  if [ "$DRY_RUN" -eq 0 ]; then
    # shellcheck disable=SC1091
    source "$BENCH_DIR/.venv/bin/activate"
    python -m pip install --upgrade pip
    python -m pip install -r "$BENCH_DIR/requirements-benchmark.txt"
    deactivate || true
  fi
else
  log "Skipping benchmark pip install"
fi

log "Running syntax and config validation"
run python3 -m py_compile \
  "$VM_DIR/app/embedding_service.py" \
  "$VM_DIR/scripts/check_all.py" \
  "$BENCH_DIR/scripts/check_services.py" \
  "$BENCH_DIR/scripts/test_vm_connection.py" \
  "$BENCH_DIR/scripts/benchmark_cli.py" \
  "$BENCH_DIR/scripts/serve_benchmark_dashboard.py" \
  "$BENCH_DIR/benchmarking/adapters/remote_embeddings.py" \
  "$BENCH_DIR/benchmarking/adapters/vector_qdrant.py" \
  "$BENCH_DIR/benchmarking/adapters/vector_pgvector.py" \
  "$BENCH_DIR/benchmarking/adapters/vector_weaviate.py"

if [ "$DRY_RUN" -eq 0 ]; then
  (cd "$BENCH_DIR" && source .venv/bin/activate && python scripts/benchmark_cli.py validate)
else
  echo "+ (cd $BENCH_DIR && python scripts/benchmark_cli.py validate)"
fi

log "Waiting briefly for HTTP services"
if [ "$DRY_RUN" -eq 0 ]; then
  python3 - <<'PY'
import time, urllib.request
for url in ['http://127.0.0.1:5000/health','http://127.0.0.1:5001/','http://127.0.0.1:5004/v1/meta']:
    ok=False; last=''
    for _ in range(30):
        try:
            with urllib.request.urlopen(url, timeout=3) as r:
                print(url, 'HTTP', r.status); ok=True; break
        except Exception as e:
            last=str(e); time.sleep(2)
    if not ok:
        print(url, 'not ready yet:', last)
PY
fi

log "Running service checks"
if [ "$DRY_RUN" -eq 0 ]; then
  if [ "$SKIP_MODEL_SMOKE" -eq 1 ]; then
    python3 - <<'PY'
import urllib.request
for url in ['http://127.0.0.1:5000/health','http://127.0.0.1:5001/','http://127.0.0.1:5004/v1/meta']:
    try:
        with urllib.request.urlopen(url, timeout=5) as r: print(url, 'OK', r.status)
    except Exception as e: print(url, 'CHECK', e)
PY
  else
    (cd "$VM_DIR" && source .venv/bin/activate && python scripts/check_all.py) || warn "Full service check had warnings. See logs and rerun: cd wns-vm-adapters && bash scripts/check_all.sh"
  fi
  (cd "$BENCH_DIR" && source .venv/bin/activate && set -a && source .env && set +a && python scripts/check_services.py) || warn "Benchmark service check had warnings"
else
  echo "+ run service checks"
fi

cat > "$ROOT/VM_SETUP_RESULT.txt" <<EOF
WNS VM setup result

VM host used for local frontend: $VM_HOST
Ports:
  5000 embedding service
  5001 Qdrant HTTP
  5002 Qdrant gRPC
  5003 PGVector/Postgres
  5004 Weaviate
  5005 Jupyter optional

Local Retreiver CMD setup:
  scripts\\windows\\Connect-Frontend-To-VM.cmd $VM_HOST

Manual fallback:
  scripts\\windows\\Configure-LocalFrontendForVM.cmd $VM_HOST
  scripts\\windows\\Start-WnsDashboard-VM.cmd

Health URLs:
  http://$VM_HOST:5000/health
  http://$VM_HOST:5001/
  http://$VM_HOST:5004/v1/meta

Logs:
  $LOG_DIR/embedding_service.log
EOF

log "Setup script finished. Read: $ROOT/VM_SETUP_RESULT.txt"
cat "$ROOT/VM_SETUP_RESULT.txt"
