#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RETRIEVER_DIR="$ROOT/Retreiver"
VM_HOST=""
SKIP_PIP=0
SKIP_DOCKER=0
SKIP_MODEL_SERVICE=0
SKIP_MODEL_SMOKE=0
DRY_RUN=0
FORCE_ENV=0
MODEL_PORT=5000
QDRANT_HTTP_PORT=5001
QDRANT_GRPC_PORT=5002
PGVECTOR_PORT=5003
WEAVIATE_HTTP_PORT=5004
WEAVIATE_GRPC_PORT=5005

usage() {
  cat <<'USAGE'
Usage:
  bash setup_all_on_vm.sh [--host VM_HOST_OR_IP] [options]

Default behavior:
  1. Detect VM host/IP if --host is omitted
  2. Write Retreiver/.env.vm.generated
  3. Create Retreiver/.env if missing, or preserve existing .env
  4. Create Python venv and install model + benchmark adapter dependencies
  5. Start Qdrant, PGVector, and Weaviate through Docker Compose
  6. Start unified FastAPI model adapter service on port 5000
  7. Run health checks and lightweight smoke tests
  8. Write VM_SETUP_RESULT.txt

Options:
  --host HOST              Public/reachable VM host or IP used in generated .env URLs
  --force-env              Replace Retreiver/.env with generated VM env
  --skip-pip               Do not create venv or install Python packages
  --skip-docker            Do not start vector DB Docker Compose services
  --skip-model-service     Do not start model adapter FastAPI service
  --skip-model-smoke       Do not call model endpoints, only health URLs
  --dry-run                Print actions and write generated files without starting services
  -h, --help               Show this help

Host-facing ports:
  5000  unified model adapter FastAPI: /embed/jina, /embed/gte, /rerank/qwen, /rerank/bge
  5001  Qdrant HTTP
  5002  Qdrant gRPC
  5003  PGVector/Postgres
  5004  Weaviate HTTP
  5005  Weaviate gRPC
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) VM_HOST="${2:-}"; shift 2 ;;
    --force-env) FORCE_ENV=1; shift ;;
    --skip-pip) SKIP_PIP=1; shift ;;
    --skip-docker) SKIP_DOCKER=1; shift ;;
    --skip-model-service) SKIP_MODEL_SERVICE=1; shift ;;
    --skip-model-smoke) SKIP_MODEL_SMOKE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

run() {
  echo "+ $*"
  if [[ "$DRY_RUN" != "1" ]]; then
    "$@"
  fi
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "MISSING command: $1" >&2
    return 1
  fi
}

detect_host() {
  if [[ -n "$VM_HOST" ]]; then
    echo "$VM_HOST"
    return
  fi
  local detected=""
  detected="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  if [[ -z "$detected" ]]; then
    detected="127.0.0.1"
  fi
  echo "$detected"
}

write_env() {
  local host="$1"
  mkdir -p "$RETRIEVER_DIR/logs" "$RETRIEVER_DIR/run"
  cat > "$RETRIEVER_DIR/.env.vm.generated" <<EOF
# Generated by setup_all_on_vm.sh
WNS_BENCHMARK_MODE=vm_remote_required

# Unified VM model adapter service, one HTTP port for model adapters
JINA_EMBEDDING_URL=http://$host:$MODEL_PORT/embed/jina
GTE_EMBEDDING_URL=http://$host:$MODEL_PORT/embed/gte
QWEN_RERANK_URL=http://$host:$MODEL_PORT/rerank/qwen
BGE_RERANK_URL=http://$host:$MODEL_PORT/rerank/bge

# Commercial APIs, fill only if using these commercial adapters
OPENAI_API_KEY=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
AWS_DEFAULT_REGION=us-east-1
AMAZON_RERANK_MODEL_ID=amazon.rerank-v1:0

# Vector DBs on VM host-facing ports
QDRANT_URL=http://$host:$QDRANT_HTTP_PORT
QDRANT_GRPC_URL=http://$host:$QDRANT_GRPC_PORT
PGVECTOR_DSN=postgresql://wns:wns_password@$host:$PGVECTOR_PORT/wns_benchmark
DATABASE_URL=postgresql://wns:wns_password@$host:$PGVECTOR_PORT/wns_benchmark
WEAVIATE_URL=http://$host:$WEAVIATE_HTTP_PORT
WEAVIATE_GRPC_URL=$host:$WEAVIATE_GRPC_PORT

# Model names and device
JINA_EMBEDDING_MODEL=jinaai/jina-embeddings-v3
GTE_EMBEDDING_MODEL=Alibaba-NLP/gte-multilingual-base
QWEN_RERANK_MODEL=Qwen/Qwen3-Reranker-4B
BGE_RERANKER_MODEL=BAAI/bge-reranker-base
WNS_MODEL_DEVICE=cuda
EOF

  if [[ "$FORCE_ENV" == "1" || ! -f "$RETRIEVER_DIR/.env" ]]; then
    run cp "$RETRIEVER_DIR/.env.vm.generated" "$RETRIEVER_DIR/.env"
    echo "Wrote $RETRIEVER_DIR/.env"
  else
    echo "Kept existing $RETRIEVER_DIR/.env. New generated values are in .env.vm.generated."
    echo "Use --force-env if you want this script to replace .env."
  fi
}

install_python_deps() {
  if [[ "$SKIP_PIP" == "1" ]]; then
    echo "Skipping Python package install."
    return
  fi
  need_cmd python3
  run python3 -m venv "$RETRIEVER_DIR/.venv-vm"
  # shellcheck source=/dev/null
  source "$RETRIEVER_DIR/.venv-vm/bin/activate"
  run python -m pip install --upgrade pip setuptools wheel
  if [[ -f "$RETRIEVER_DIR/requirements-benchmark.txt" ]]; then
    run python -m pip install -r "$RETRIEVER_DIR/requirements-benchmark.txt"
  fi
  run python -m pip install fastapi 'uvicorn[standard]' sentence-transformers torch transformers numpy pydantic
}

start_vector_dbs() {
  if [[ "$SKIP_DOCKER" == "1" ]]; then
    echo "Skipping Docker vector DB startup."
    return
  fi
  need_cmd docker
  run docker compose -f "$RETRIEVER_DIR/docker-compose.benchmark.yml" up -d qdrant postgres-pgvector weaviate
}

start_model_service() {
  if [[ "$SKIP_MODEL_SERVICE" == "1" ]]; then
    echo "Skipping model adapter service startup."
    return
  fi
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "+ start unified model adapter service on port $MODEL_PORT"
    return
  fi
  if [[ ! -x "$RETRIEVER_DIR/.venv-vm/bin/python" ]]; then
    echo "Missing VM venv. Run without --skip-pip first." >&2
    exit 1
  fi
  if [[ -f "$RETRIEVER_DIR/run/wns_vm_adapter_service.pid" ]]; then
    old_pid="$(cat "$RETRIEVER_DIR/run/wns_vm_adapter_service.pid" || true)"
    if [[ -n "$old_pid" ]] && kill -0 "$old_pid" 2>/dev/null; then
      kill "$old_pid" || true
      sleep 2
    fi
  fi
  # shellcheck source=/dev/null
  source "$RETRIEVER_DIR/.venv-vm/bin/activate"
  set -a
  # shellcheck source=/dev/null
  source "$RETRIEVER_DIR/.env.vm.generated"
  set +a
  nohup uvicorn scripts.wns_vm_adapter_service:app --app-dir "$RETRIEVER_DIR" --host 0.0.0.0 --port "$MODEL_PORT" > "$RETRIEVER_DIR/logs/wns_vm_adapter_service.log" 2>&1 &
  echo $! > "$RETRIEVER_DIR/run/wns_vm_adapter_service.pid"
  echo "Started model adapter service: PID $(cat "$RETRIEVER_DIR/run/wns_vm_adapter_service.pid")"
}

http_wait() {
  local url="$1"
  local name="$2"
  local attempts="${3:-30}"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "+ check $name: $url"
    return 0
  fi
  for _ in $(seq 1 "$attempts"); do
    if curl -fsS --max-time 5 "$url" >/dev/null 2>&1; then
      echo "OK: $name"
      return 0
    fi
    sleep 2
  done
  echo "CHECK FAILED: $name at $url" >&2
  return 1
}

tcp_wait() {
  local host="$1"
  local port="$2"
  local name="$3"
  local attempts="${4:-30}"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "+ check $name: $host:$port"
    return 0
  fi
  for _ in $(seq 1 "$attempts"); do
    if python3 - "$host" "$port" <<'PY' >/dev/null 2>&1
import socket, sys
host, port = sys.argv[1], int(sys.argv[2])
with socket.create_connection((host, port), timeout=5):
    pass
PY
    then
      echo "OK: $name"
      return 0
    fi
    sleep 2
  done
  echo "CHECK FAILED: $name at $host:$port" >&2
  return 1
}

post_smoke() {
  local url="$1"
  local name="$2"
  local payload="$3"
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "+ smoke $name: $url"
    return 0
  fi
  curl -fsS --max-time 180 -X POST "$url" -H 'Content-Type: application/json' -d "$payload" >/tmp/wns_smoke_response.json
  python - <<'PY'
import json
from pathlib import Path
p = Path('/tmp/wns_smoke_response.json')
data = json.loads(p.read_text())
if not (data.get('embeddings') or data.get('data') or data.get('scores') or data.get('results')):
    raise SystemExit(f'Unexpected smoke response keys: {sorted(data.keys())}')
print('OK smoke response keys:', ','.join(sorted(data.keys())))
PY
  echo "OK: $name smoke"
}

run_checks() {
  local host="$1"
  echo "Running readiness checks..."
  http_wait "http://127.0.0.1:$MODEL_PORT/health" "model adapter health" 45
  http_wait "http://127.0.0.1:$QDRANT_HTTP_PORT/" "Qdrant HTTP" 20
  tcp_wait "127.0.0.1" "$PGVECTOR_PORT" "PGVector/Postgres" 20
  http_wait "http://127.0.0.1:$WEAVIATE_HTTP_PORT/v1/meta" "Weaviate HTTP" 20

  if [[ "$DRY_RUN" != "1" ]] && command -v python3 >/dev/null 2>&1; then
    python3 -m py_compile "$RETRIEVER_DIR/scripts/wns_vm_adapter_service.py" "$RETRIEVER_DIR/benchmarking/core/runner.py" "$RETRIEVER_DIR/benchmarking/core/registry.py" || true
    (cd "$RETRIEVER_DIR" && python3 scripts/benchmark_cli.py validate) || true
  fi

  if [[ "$SKIP_MODEL_SMOKE" == "1" || "$SKIP_MODEL_SERVICE" == "1" ]]; then
    echo "Skipping model smoke tests."
  else
    post_smoke "http://127.0.0.1:$MODEL_PORT/embed/jina" "Jina embedding" '{"texts":["refund policy","flight change"]}' || true
    post_smoke "http://127.0.0.1:$MODEL_PORT/embed/gte" "GTE embedding" '{"texts":["refund policy","flight change"]}' || true
    post_smoke "http://127.0.0.1:$MODEL_PORT/rerank/bge" "BGE rerank" '{"query":"refund policy","documents":["refund policy details","seat selection rules"],"top_k":2}' || true
    if [[ "${WNS_ENABLE_QWEN_SMOKE:-0}" == "1" ]]; then
      post_smoke "http://127.0.0.1:$MODEL_PORT/rerank/qwen" "Qwen rerank" '{"query":"refund policy","documents":["refund policy details","seat selection rules"],"top_k":2}' || true
    else
      echo "Qwen smoke skipped by default because Qwen3:4B download/load is heavy. Set WNS_ENABLE_QWEN_SMOKE=1 to preload/test it."
    fi
  fi
}

write_result() {
  local host="$1"
  cat > "$ROOT/VM_SETUP_RESULT.txt" <<EOF
WNS VM setup completed/generated.

Health URLs:
  Model adapter: http://$host:$MODEL_PORT/health
  Jina embedding: http://$host:$MODEL_PORT/embed/jina
  GTE embedding: http://$host:$MODEL_PORT/embed/gte
  Qwen rerank: http://$host:$MODEL_PORT/rerank/qwen
  BGE rerank: http://$host:$MODEL_PORT/rerank/bge
  Qdrant: http://$host:$QDRANT_HTTP_PORT
  PGVector: postgresql://wns:wns_password@$host:$PGVECTOR_PORT/wns_benchmark
  Weaviate: http://$host:$WEAVIATE_HTTP_PORT/v1/meta

Generated env:
  $RETRIEVER_DIR/.env.vm.generated

If Retreiver/.env already existed, it was preserved unless --force-env was used.
Add OPENAI_API_KEY and AWS credentials in Retreiver/.env only if running commercial OpenAI/Amazon adapters.
EOF
  echo "Wrote $ROOT/VM_SETUP_RESULT.txt"
}

main() {
  VM_HOST="$(detect_host)"
  echo "WNS VM setup root: $ROOT"
  echo "Using VM host: $VM_HOST"
  write_env "$VM_HOST"
  install_python_deps
  start_vector_dbs
  start_model_service
  run_checks "$VM_HOST"
  write_result "$VM_HOST"
  echo "Done."
}

main "$@"
